#!/bin/sh

# zSecret - by Zorge.R - motofan.ru
# plese don't modify code.

rspath=${0%/*}

if [ ! -f $rspath/firststart ]
then
	showNotify "zSecret" "First start detected"  1 3
	showQ "zSecret" "Create Secret folder on microSD?" 1
	zsans=$?
	if [ $zsans -eq 1 ]
	then
		mkdir -p /mmc/mmca1/.secret
		if [ -d /mmc/mmca1/.secret ]
		then
			showQ "zSecret" "Secret folder created on microSD. zSecret will be restart." 2
			touch $rspath/firststart
			echo -ne /mmc/mmca1 > $rspath/path
			$0
		else
			showQ "zSecret" "can't create on microSD. Create in Phone memory?" 1
			zsans2=$?
			if [ $zsans2 -eq 1 ]
			then
				mkdir -p /ezxlocal/download/mystuff/.secret
				if [ -d /ezxlocal/download/mystuff/.secret ]
				then
					showQ "zSecret" "Secret folder created in Phone memory. zSecret will be restart." 2
					touch $rspath/firststart
					echo -ne /ezxlocal/download/mystuff > $rspath/path
					$0
				else
					showQ "zSecret" "can't create in Phone too. Will be exit" 2
					exit
				fi
			else
				showQ "zSecret" "Will be exit." 2
				exit
			fi
		fi
	else
		showQ "zSecret" "Create Secret folder in Phone memory?" 1
		zsans3=$?
		if [ $zsans3 -eq 1 ]
		then
			mkdir -p /ezxlocal/download/mystuff/.secret
			if [ -d /ezxlocal/download/mystuff/.secret ]
			then
				showQ "zSecret" "Secret folder created on Phone memory. zSecret will be restart." 2
				touch $rspath/firststart
				echo -ne /ezxlocal/download/mystuff > $rspath/path
				$0
			else
				showQ "zSecret" "can't create in Phone. Will be exit" 2
				exit
			fi
		else
			showQ "zSecret" "Will be exit." 2
			exit
		fi
	fi
else
	if [ ! -f /ezxlocal/zsecrpass ]
	then
		showQ "zSecret" "Password undefined. Enter NEW password in next window." 2
		zspass=`showTextEntry zSecret "Enter Any password:"`
		if [ $? != 0 ] && [ "$zspass" != "" ]
		then
			echo -ne $zspass > /ezxlocal/zsecrpass
			showQ "zSecret" "NEW Password stored. zSecret will be restart." 2
			$0
		else
			showQ "zSecret" "You must enter Any password! Exit." 2
			exit
		fi
	else
		zsdir=`cat $rspath/path`
		zspass=`cat /ezxlocal/zsecrpass`
		zspasscheck=`showTextEntry zSecret "Enter password:"`
		if [ $? != 0 ] && [ "$zspasscheck" != "" ] && [ "$zspasscheck" = "$zspass" ]
		then
			showNotisy "zSecret" "Pasword correct! zSecret will be Start." 1 1
			showRadio "zSecret" "select action" "Hide \ unHide folder" "Reset zSecret" "about"
			zsans4=$?
			if [ $zsans4 -eq 1 ]
			then
				if [ -d $zsdir/.secret ]
				then
					mv $zsdir/.secret $zsdir/secret
					showQ "zSecret" "Success. Secret folder will SHOW in File Manager." 2
				else
					if [ -d $zsdir/secret ]
					then
						mv $zsdir/secret $zsdir/.secret
						showQ "zSecret" "Success. Secret folder are HIDE." 2
					else
						showQ "zSecret" "Cant find Secret folder! Reset zSecret please!" 2
						$0
					fi
				fi
			elif [ $zsans4 -eq 2 ]
			then
				showQ "zSecret" "WARNING: password and folder setting will be reset. Continue?" 1
				zsansME=$?
				if [ $zsansME -eq 1 ]
				then
					rm /ezxlocal/zsecrpass
					rm $rspath/firststart
					rm $rspath/path
					showQ "zSecret" "All config and password reset. zSecret will be restart." 2
					$0
				else
					showQ "zSecret" "Ok. As You well." 2
					$0
				fi
			elif [ $zsans4 -eq 3 ]
			then
				showQ "zSecret" "This is a simple util for magx Phone, to password access in Secret folder. Zorge.R - motofan.ru" 2
				$0
			else
				showQ "zSecret" "Will be Exit." 2
				exit
			fi
		else
			showQ "zSecret" "Password incorrect! Exit." 2
			exit
		fi
 	fi
fi


